import { computePrimaryRole } from './rules';
import { Employee, LocationInfo, ShiftRequest } from './types';

export const MANAGER_MASTER_PASSWORD = 'admin';

export const LOCATIONS: LocationInfo[] = [
  {
    id: 'gazzada',
    name: 'Nicora Garden Gazzada',
    shortName: 'Gazzada',
    city: 'Gazzada Schianno (VA)',
    address: 'Via Gallarate 26, 21045 Gazzada Schianno (VA)',
    phone: '0332 461144',
    defaultStaffCount: 9,
  },
  {
    id: 'varese',
    name: 'Nicora Garden Varese',
    shortName: 'Varese',
    city: 'Varese Centro',
    address: 'Via Daverio 46, 21100 Varese (VA)',
    phone: '0332 312101',
    defaultStaffCount: 16,
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  // ==========================================
  // --- GAZZADA (9 Collaboratori Reali + Titolare) ---
  // ==========================================
  {
    id: 'emp-gz-1',
    name: 'Sabrina',
    locationId: 'gazzada',
    role: computePrimaryRole({ Cassa: 10, Fioreria: 5 }, 'gazzada', 'emp-gz-1', 'Sabrina'),
    skills: { Cassa: 10, Fioreria: 5, Emporio: 0, 'Serra Calda': 0, 'Serra Fredda': 0 },
    avatar: 'SA',
    email: 'sabrina@nicoragarden.it',
    phone: '340 1000001',
    password: '123',
    contractHours: 40,
    color: '#ec4899', // Pink (Cassa)
    isActive: true,
  },
  {
    id: 'emp-gz-2',
    name: 'Eleonora',
    locationId: 'gazzada',
    role: computePrimaryRole({ Cassa: 8, Fioreria: 10, 'Serra Calda': 4 }, 'gazzada', 'emp-gz-2', 'Eleonora'),
    skills: { Fioreria: 10, Cassa: 8, 'Serra Calda': 4, Emporio: 0, 'Serra Fredda': 0 },
    avatar: 'EL',
    email: 'eleonora@nicoragarden.it',
    phone: '340 1000002',
    password: '123',
    contractHours: 40,
    color: '#f97316', // Orange/Salmon (Fioreria)
    isActive: true,
  },
  {
    id: 'emp-gz-3',
    name: 'Matteo F.',
    locationId: 'gazzada',
    role: computePrimaryRole({ Fioreria: 8, Cassa: 7, 'Serra Calda': 4, 'Serra Fredda': 4 }, 'gazzada', 'emp-gz-3', 'Matteo F.'),
    skills: { Fioreria: 8, Cassa: 7, 'Serra Calda': 4, 'Serra Fredda': 4, Emporio: 0 },
    avatar: 'MF',
    email: 'matteo.f@nicoragarden.it',
    phone: '340 1000003',
    password: '123',
    contractHours: 40,
    color: '#f97316', // Fioreria
    isActive: true,
  },
  {
    id: 'emp-gz-4',
    name: 'Vittore Nicora',
    locationId: 'gazzada',
    role: 'Emporio',
    skills: { Emporio: 10, 'Serra Calda': 10, 'Serra Fredda': 10, Cassa: 8, Fioreria: 8 },
    avatar: 'VN',
    email: 'vittore@nicora.eu',
    phone: '335 1122334',
    password: 'admin',
    isManager: true,
    isOwner: true,
    contractHours: 0,
    color: '#0284c7',
    isActive: true,
  },
  {
    id: 'emp-gz-5',
    name: 'Daniela',
    locationId: 'gazzada',
    role: computePrimaryRole({ 'Serra Fredda': 9, 'Serra Calda': 6, Emporio: 5, Cassa: 5, Fioreria: 3 }, 'gazzada', 'emp-gz-5', 'Daniela'),
    skills: { 'Serra Fredda': 9, 'Serra Calda': 6, Emporio: 5, Cassa: 5, Fioreria: 3 },
    avatar: 'DA',
    email: 'daniela@nicoragarden.it',
    phone: '340 1000005',
    password: '123',
    contractHours: 40,
    color: '#22c55e', // Green (Serra Fredda)
    isActive: true,
  },
  {
    id: 'emp-gz-6',
    name: 'Ginevra',
    locationId: 'gazzada',
    role: computePrimaryRole({ 'Serra Fredda': 8, 'Serra Calda': 5 }, 'gazzada', 'emp-gz-6', 'Ginevra'),
    skills: { 'Serra Fredda': 8, 'Serra Calda': 5, Emporio: 0, Cassa: 0, Fioreria: 0 },
    avatar: 'GI',
    email: 'ginevra@nicoragarden.it',
    phone: '340 1000006',
    password: '123',
    contractHours: 40,
    color: '#22c55e', // Green
    isActive: true,
  },
  {
    id: 'emp-gz-7',
    name: 'Denis',
    locationId: 'gazzada',
    role: computePrimaryRole({ Emporio: 9, 'Serra Calda': 9, 'Serra Fredda': 9 }, 'gazzada', 'emp-gz-7', 'Denis'),
    skills: { 'Serra Calda': 9, 'Serra Fredda': 9, Emporio: 9, Cassa: 0, Fioreria: 0 },
    avatar: 'DE',
    email: 'denis@nicoragarden.it',
    phone: '340 1000007',
    password: '123',
    contractHours: 40,
    color: '#eab308', // Giallo (Serra Calda)
    isActive: true,
  },
  {
    id: 'emp-gz-8',
    name: 'Laura',
    locationId: 'gazzada',
    role: computePrimaryRole({ 'Serra Calda': 10, 'Serra Fredda': 6 }, 'gazzada', 'emp-gz-8', 'Laura'),
    skills: { 'Serra Calda': 10, 'Serra Fredda': 6, Emporio: 0, Cassa: 0, Fioreria: 0 },
    avatar: 'LA',
    email: 'laura@nicoragarden.it',
    phone: '340 1000008',
    password: '123',
    contractHours: 40,
    color: '#eab308', // Giallo (Serra Calda)
    isActive: true,
  },
  {
    id: 'emp-gz-9',
    name: 'Ivano',
    locationId: 'gazzada',
    role: computePrimaryRole({ Emporio: 10, 'Serra Fredda': 8, 'Serra Calda': 7, Cassa: 7, Fioreria: 6 }, 'gazzada', 'emp-gz-9', 'Ivano'),
    skills: { Emporio: 10, 'Serra Fredda': 8, 'Serra Calda': 7, Cassa: 7, Fioreria: 6 },
    avatar: 'IV',
    email: 'ivano@nicoragarden.it',
    phone: '340 1000009',
    password: '123',
    contractHours: 40,
    color: '#06b6d4', // Celeste / Azzurro (Emporio / Area Tecnica)
    isActive: true,
  },
  {
    id: 'emp-gz-10',
    name: 'Marco',
    locationId: 'gazzada',
    role: computePrimaryRole({ 'Serra Fredda': 10, 'Serra Calda': 5 }, 'gazzada', 'emp-gz-10', 'Marco'),
    skills: { 'Serra Fredda': 10, 'Serra Calda': 5, Emporio: 0, Cassa: 0, Fioreria: 0 },
    avatar: 'MA',
    email: 'marco.gz@nicoragarden.it',
    phone: '340 1000010',
    password: '123',
    contractHours: 40,
    color: '#22c55e',
    isActive: true,
  },
  {
    id: 'emp-gz-11',
    name: 'Mattia',
    locationId: 'gazzada',
    role: 'Serra Fredda',
    skills: { 'Serra Fredda': 8, 'Serra Calda': 7, Emporio: 5, Cassa: 4, Fioreria: 3 },
    avatar: 'MT',
    email: 'mattia@nicoragarden.it',
    phone: '340 1000011',
    password: '123',
    contractHours: 40,
    color: '#64748b',
    isActive: false,
  },
  {
    id: 'emp-gz-12',
    name: 'Davide',
    locationId: 'gazzada',
    role: 'Cassa',
    skills: { Cassa: 8, 'Serra Fredda': 6, 'Serra Calda': 6, Fioreria: 5, Emporio: 4 },
    avatar: 'DV',
    email: 'davide@nicoragarden.it',
    phone: '340 1000012',
    password: '123',
    contractHours: 20,
    color: '#ec4899',
    isActive: false,
  },

  // ==========================================
  // --- VARESE (16 Collaboratori Reali) ---
  // ==========================================
  {
    id: 'emp-va-1',
    name: 'Stefania',
    locationId: 'varese',
    role: computePrimaryRole({ Cassa: 10, Decor: 4 }, 'varese', 'emp-va-1', 'Stefania'),
    skills: { Cassa: 10, Decor: 4, Fioreria: 0, Emporio: 0, 'Serra Calda': 0, 'Serra Fredda': 0, Natale: 0 },
    avatar: 'ST',
    email: 'stefania@nicoragarden.it',
    phone: '340 2000001',
    password: '123',
    isManager: true,
    contractHours: 40,
    color: '#dc2626', // Red (Cassa VA)
    isActive: true,
  },
  {
    id: 'emp-va-2',
    name: 'Katja',
    locationId: 'varese',
    role: computePrimaryRole({ Fioreria: 10, Cassa: 8, 'Serra Calda': 6, Decor: 6, Natale: 4 }, 'varese', 'emp-va-2', 'Katja'),
    skills: { Fioreria: 10, Cassa: 8, 'Serra Calda': 6, Decor: 6, Natale: 4, Emporio: 0, 'Serra Fredda': 0 },
    avatar: 'KA',
    email: 'katja@nicoragarden.it',
    phone: '340 2000002',
    password: '123',
    contractHours: 40,
    color: '#f472b6', // Pink (Fioreria)
    isActive: true,
  },
  {
    id: 'emp-va-3',
    name: 'Luisa',
    locationId: 'varese',
    role: computePrimaryRole({ Fioreria: 8, 'Serra Calda': 4 }, 'varese', 'emp-va-3', 'Luisa'),
    skills: { Fioreria: 8, 'Serra Calda': 4, Cassa: 0, Emporio: 0, 'Serra Fredda': 0, Decor: 0, Natale: 0 },
    avatar: 'LU',
    email: 'luisa@nicoragarden.it',
    phone: '340 2000003',
    password: '123',
    contractHours: 40,
    color: '#f472b6',
    isActive: true,
  },
  {
    id: 'emp-va-4',
    name: 'Giancarla',
    locationId: 'varese',
    role: computePrimaryRole({ Decor: 10, Natale: 10, Cassa: 7, 'Serra Calda': 6 }, 'varese', 'emp-va-4', 'Giancarla'),
    skills: { Decor: 10, Natale: 10, Cassa: 7, 'Serra Calda': 6, Fioreria: 0, Emporio: 0, 'Serra Fredda': 0 },
    avatar: 'GC',
    email: 'giancarla@nicoragarden.it',
    phone: '340 2000004',
    password: '123',
    contractHours: 40,
    color: '#a855f7', // Decor
    isActive: true,
  },
  {
    id: 'emp-va-5',
    name: 'Giovanna',
    locationId: 'varese',
    role: computePrimaryRole({ Decor: 8, Natale: 8, Cassa: 6, Fioreria: 6, 'Serra Calda': 4 }, 'varese', 'emp-va-5', 'Giovanna'),
    skills: { Decor: 8, Natale: 8, Cassa: 6, Fioreria: 6, 'Serra Calda': 4, Emporio: 0, 'Serra Fredda': 0 },
    avatar: 'GO',
    email: 'giovanna@nicoragarden.it',
    phone: '340 2000005',
    password: '123',
    contractHours: 40,
    color: '#a855f7', // Decor (Rosa scuro/Viola)
    isActive: true,
  },
  {
    id: 'emp-va-6',
    name: 'Matteo Z.',
    locationId: 'varese',
    role: computePrimaryRole({ Emporio: 10, Natale: 10, Decor: 4 }, 'varese', 'emp-va-6', 'Matteo Z.'),
    skills: { Emporio: 10, Natale: 10, Decor: 4, Cassa: 0, Fioreria: 0, 'Serra Calda': 0, 'Serra Fredda': 0 },
    avatar: 'MZ',
    email: 'matteo.z@nicoragarden.it',
    phone: '340 2000006',
    password: '123',
    contractHours: 40,
    color: '#78716c', // Emporio
    isActive: true,
  },
  {
    id: 'emp-va-luigi',
    name: 'Luigi',
    locationId: 'varese',
    role: computePrimaryRole({ Natale: 6 }, 'varese', 'emp-va-luigi', 'Luigi'),
    skills: { Natale: 6, Cassa: 0, Fioreria: 0, Emporio: 0, 'Serra Calda': 0, 'Serra Fredda': 0, Decor: 0 },
    avatar: 'LG',
    email: 'luigi@nicoragarden.it',
    phone: '340 2000021',
    password: '123',
    contractHours: 40,
    color: '#ea580c', // Orange (Natale)
    isActive: true,
  },
  {
    id: 'emp-va-7',
    name: 'Stefano',
    locationId: 'varese',
    role: computePrimaryRole({ 'Serra Fredda': 8, Natale: 8, Emporio: 4, 'Serra Calda': 4 }, 'varese', 'emp-va-7', 'Stefano'),
    skills: { 'Serra Fredda': 8, Natale: 8, Emporio: 4, 'Serra Calda': 4, Cassa: 0, Fioreria: 0, Decor: 0 },
    avatar: 'SO',
    email: 'stefano@nicoragarden.it',
    phone: '340 2000007',
    password: '123',
    contractHours: 40,
    color: '#22c55e', // Green (Serra Fredda)
    isActive: true,
  },
  {
    id: 'emp-va-ivan',
    name: 'Ivan',
    locationId: 'varese',
    role: computePrimaryRole({ Natale: 6, Fioreria: 4, 'Serra Calda': 4, Decor: 2 }, 'varese', 'emp-va-ivan', 'Ivan'),
    skills: { Natale: 6, Fioreria: 4, 'Serra Calda': 4, Decor: 2, Cassa: 0, Emporio: 0, 'Serra Fredda': 0 },
    avatar: 'IV',
    email: 'ivan.va@nicoragarden.it',
    phone: '340 2000022',
    password: '123',
    contractHours: 40,
    color: '#ea580c', // Orange (Natale)
    isActive: true,
  },
  {
    id: 'emp-va-8',
    name: 'Andrea',
    locationId: 'varese',
    role: computePrimaryRole({ Emporio: 8 }, 'varese', 'emp-va-8', 'Andrea'),
    skills: { Emporio: 8, Cassa: 0, Fioreria: 0, 'Serra Calda': 0, 'Serra Fredda': 0, Decor: 0, Natale: 0 },
    avatar: 'AN',
    email: 'andrea@nicoragarden.it',
    phone: '340 2000008',
    password: '123',
    contractHours: 40,
    color: '#78716c', // Kaki/Stone (Emporio)
    isActive: true,
  },
  {
    id: 'emp-va-9',
    name: 'Francesca',
    locationId: 'varese',
    role: computePrimaryRole({ 'Serra Calda': 10, 'Serra Fredda': 6, Emporio: 2 }, 'varese', 'emp-va-9', 'Francesca'),
    skills: { 'Serra Calda': 10, 'Serra Fredda': 6, Emporio: 2, Cassa: 0, Fioreria: 0, Decor: 0, Natale: 0 },
    avatar: 'FR',
    email: 'francesca@nicoragarden.it',
    phone: '340 2000009',
    password: '123',
    contractHours: 40,
    color: '#eab308', // Giallo (Serra Calda)
    isActive: true,
  },
  {
    id: 'emp-va-10',
    name: 'Cinzia',
    locationId: 'varese',
    role: computePrimaryRole({ 'Serra Calda': 8, Decor: 8, Natale: 8, Cassa: 4 }, 'varese', 'emp-va-10', 'Cinzia'),
    skills: { 'Serra Calda': 8, Decor: 8, Natale: 8, Cassa: 4, Fioreria: 0, Emporio: 0, 'Serra Fredda': 0 },
    avatar: 'CI',
    email: 'cinzia@nicoragarden.it',
    phone: '340 2000010',
    password: '123',
    contractHours: 24,
    color: '#eab308', // Giallo (Serra Calda)
    isActive: true,
  },
  {
    id: 'emp-va-11',
    name: 'Elina',
    locationId: 'varese',
    role: computePrimaryRole({ 'Serra Fredda': 6, 'Serra Calda': 6, Emporio: 4 }, 'varese', 'emp-va-11', 'Elina'),
    skills: { 'Serra Fredda': 6, 'Serra Calda': 6, Emporio: 4, Cassa: 0, Fioreria: 0, Decor: 0, Natale: 0 },
    avatar: 'EL',
    email: 'elina.va@nicoragarden.it',
    phone: '340 2000011',
    password: '123',
    contractHours: 24,
    color: '#22c55e',
    isActive: true,
    isMobile: true,
  },
  {
    id: 'emp-va-12',
    name: 'Gionata',
    locationId: 'varese',
    role: computePrimaryRole({ 'Serra Fredda': 10, 'Serra Calda': 4, Emporio: 4 }, 'varese', 'emp-va-12', 'Gionata'),
    skills: { 'Serra Fredda': 10, 'Serra Calda': 4, Emporio: 4, Cassa: 0, Fioreria: 0, Decor: 0, Natale: 0 },
    avatar: 'GN',
    email: 'gionata@nicoragarden.it',
    phone: '340 2000012',
    password: '123',
    contractHours: 40,
    color: '#22c55e',
    isActive: true,
  },
  {
    id: 'emp-va-13',
    name: 'Giulio',
    locationId: 'varese',
    role: computePrimaryRole({ 'Serra Fredda': 9, Emporio: 4 }, 'varese', 'emp-va-13', 'Giulio'),
    skills: { 'Serra Fredda': 9, Emporio: 4, Cassa: 0, Fioreria: 0, 'Serra Calda': 0, Decor: 0, Natale: 0 },
    avatar: 'GL',
    email: 'giulio@nicoragarden.it',
    phone: '340 2000013',
    password: '123',
    contractHours: 40,
    color: '#22c55e',
    isActive: true,
  },
  {
    id: 'emp-va-14',
    name: 'Carlo',
    locationId: 'varese',
    role: computePrimaryRole({}, 'varese', 'emp-va-14', 'Carlo'),
    skills: { Cassa: 0, Fioreria: 0, Emporio: 0, 'Serra Calda': 0, 'Serra Fredda': 0, Decor: 0, Natale: 0 },
    avatar: 'CA',
    email: 'carlo@nicoragarden.it',
    phone: '340 2000014',
    password: '123',
    contractHours: 40,
    color: '#38bdf8', // Light Blue (Supporto/Corsia Vivaio)
    isActive: true,
  },
  {
    id: 'emp-va-15',
    name: 'Sara',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 8, Decor: 7, Fioreria: 6, 'Serra Calda': 5, 'Serra Fredda': 5, Emporio: 4, Natale: 3 },
    avatar: 'SR',
    email: 'sara@nicoragarden.it',
    phone: '340 2000015',
    password: '123',
    contractHours: 30,
    color: '#dc2626',
    isActive: false,
  },
  {
    id: 'emp-va-16',
    name: 'Arianna',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 9, Decor: 6, Fioreria: 5, 'Serra Calda': 5, 'Serra Fredda': 5, Emporio: 4, Natale: 2 },
    avatar: 'AR',
    email: 'arianna@nicoragarden.it',
    phone: '340 2000016',
    password: '123',
    contractHours: 24,
    color: '#dc2626',
    isActive: false,
  },
  {
    id: 'emp-va-17',
    name: 'Gaia',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { 'Serra Fredda': 8, Cassa: 7, Fioreria: 6, Decor: 6, 'Serra Calda': 6, Emporio: 4, Natale: 3 },
    avatar: 'GA',
    email: 'gaia@nicoragarden.it',
    phone: '340 2000017',
    password: '123',
    contractHours: 24,
    color: '#22c55e',
    isActive: false,
  },
  {
    id: 'emp-va-18',
    name: 'Claudio',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { 'Serra Fredda': 9, 'Serra Calda': 7, Emporio: 4, Decor: 4, Cassa: 3, Fioreria: 2, Natale: 3 },
    avatar: 'CL',
    email: 'claudio@nicoragarden.it',
    phone: '340 2000018',
    password: '123',
    contractHours: 40,
    color: '#22c55e',
    isActive: false,
  },
  {
    id: 'emp-va-19',
    name: 'Debora',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 9, Fioreria: 5, Decor: 5, 'Serra Calda': 4, 'Serra Fredda': 4, Emporio: 3, Natale: 2 },
    avatar: 'DB',
    email: 'debora@nicoragarden.it',
    phone: '340 2000019',
    password: '123',
    contractHours: 20,
    color: '#dc2626',
    isActive: false,
  },
  {
    id: 'emp-va-20',
    name: 'Nancy',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 9, Fioreria: 7, Decor: 6, 'Serra Calda': 4, 'Serra Fredda': 4, Emporio: 3, Natale: 2 },
    avatar: 'NA',
    email: 'nancy@nicoragarden.it',
    phone: '340 2000020',
    password: '123',
    contractHours: 20,
    color: '#dc2626',
    isActive: false,
  },
];

// Richieste iniziali vuote alla consegna del database
export const INITIAL_REQUESTS: ShiftRequest[] = [];

