import { Employee, LocationInfo, ShiftRequest } from './types';

export const MANAGER_MASTER_PASSWORD = 'admin';

export const LOCATIONS: LocationInfo[] = [
  {
    id: 'gazzada',
    name: 'Nicora Garden Gazzada',
    shortName: 'Gazzada',
    city: 'Gazzada Schianno (VA)',
    address: 'Via Gallarate 26, 21045 Gazzada Schianno (VA)',
    phone: '0332 461144',
    defaultStaffCount: 10,
  },
  {
    id: 'varese',
    name: 'Nicora Garden Varese',
    shortName: 'Varese',
    city: 'Varese Centro',
    address: 'Via Daverio 46, 21100 Varese (VA)',
    phone: '0332 312101',
    defaultStaffCount: 16,
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  // ==========================================
  // --- GAZZADA (12 Collaboratori Reali) ---
  // ==========================================
  {
    id: 'emp-gz-1',
    name: 'Sabrina',
    locationId: 'gazzada',
    role: 'Cassa',
    skills: { Cassa: 10, Fioreria: 7, Decor: 6, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'SA',
    email: 'sabrina@nicoragarden.it',
    phone: '340 1000001',
    password: '123',
    contractHours: 40,
    color: '#ec4899', // Pink (Cassa)
  },
  {
    id: 'emp-gz-2',
    name: 'Eleonora',
    locationId: 'gazzada',
    role: 'Fioreria',
    skills: { Cassa: 6, Fioreria: 10, Decor: 8, 'Serra Calda': 5, 'Serra Fredda': 4 },
    avatar: 'EL',
    email: 'eleonora@nicoragarden.it',
    phone: '340 1000002',
    password: '123',
    contractHours: 40,
    color: '#f97316', // Orange (Fioreria)
  },
  {
    id: 'emp-gz-3',
    name: 'Teo',
    locationId: 'gazzada',
    role: 'Serra Calda',
    skills: { Cassa: 5, Fioreria: 4, Decor: 5, 'Serra Calda': 10, 'Serra Fredda': 8 },
    avatar: 'TE',
    email: 'teo@nicoragarden.it',
    phone: '340 1000003',
    password: '123',
    contractHours: 40,
    color: '#eab308', // Yellow (Serra Calda)
  },
  {
    id: 'emp-gz-4',
    name: 'Vittore Nicora',
    locationId: 'gazzada',
    role: 'Serra Calda',
    skills: { Cassa: 8, Fioreria: 8, Decor: 8, 'Serra Calda': 10, 'Serra Fredda': 10 },
    avatar: 'VN',
    email: 'vittore@nicoragarden.it',
    phone: '335 1122334',
    password: 'admin',
    isManager: true,
    contractHours: 40,
    color: '#eab308',
  },
  {
    id: 'emp-gz-5',
    name: 'Daniela',
    locationId: 'gazzada',
    role: 'Fioreria',
    skills: { Cassa: 7, Fioreria: 9, Decor: 8, 'Serra Calda': 5, 'Serra Fredda': 4 },
    avatar: 'DA',
    email: 'daniela@nicoragarden.it',
    phone: '340 1000005',
    password: '123',
    contractHours: 30,
    color: '#f97316', // Orange (Fioreria/Decor)
  },
  {
    id: 'emp-gz-6',
    name: 'Ginevra',
    locationId: 'gazzada',
    role: 'Serra Fredda',
    skills: { Cassa: 4, Fioreria: 4, Decor: 5, 'Serra Calda': 8, 'Serra Fredda': 9 },
    avatar: 'GI',
    email: 'ginevra@nicoragarden.it',
    phone: '340 1000006',
    password: '123',
    contractHours: 40,
    color: '#22c55e', // Green
  },
  {
    id: 'emp-gz-7',
    name: 'Denis',
    locationId: 'gazzada',
    role: 'Decor',
    skills: { Cassa: 3, Fioreria: 2, Decor: 4, 'Serra Calda': 7, 'Serra Fredda': 9 },
    avatar: 'DE',
    email: 'denis@nicoragarden.it',
    phone: '340 1000007',
    password: '123',
    contractHours: 40,
    color: '#06b6d4', // Area Tecnica / Logistics
  },
  {
    id: 'emp-gz-8',
    name: 'Laura',
    locationId: 'gazzada',
    role: 'Cassa',
    skills: { Cassa: 8, Fioreria: 5, Decor: 6, 'Serra Calda': 8, 'Serra Fredda': 5 },
    avatar: 'LA',
    email: 'laura@nicoragarden.it',
    phone: '340 1000008',
    password: '123',
    contractHours: 40,
    color: '#eab308',
  },
  {
    id: 'emp-gz-9',
    name: 'Ivano',
    locationId: 'gazzada',
    role: 'Serra Fredda',
    skills: { Cassa: 3, Fioreria: 2, Decor: 4, 'Serra Calda': 6, 'Serra Fredda': 9 },
    avatar: 'IV',
    email: 'ivano@nicoragarden.it',
    phone: '340 1000009',
    password: '123',
    contractHours: 40,
    color: '#06b6d4',
  },
  {
    id: 'emp-gz-10',
    name: 'Marco',
    locationId: 'gazzada',
    role: 'Serra Fredda',
    skills: { Cassa: 4, Fioreria: 3, Decor: 4, 'Serra Calda': 8, 'Serra Fredda': 10 },
    avatar: 'MA',
    email: 'marco.gz@nicoragarden.it',
    phone: '340 1000010',
    password: '123',
    contractHours: 40,
    color: '#22c55e',
    isActive: true,
  },
  {
    id: 'emp-gz-11',
    name: 'Mattia',
    locationId: 'gazzada',
    role: 'Decor',
    skills: { Cassa: 4, Fioreria: 3, Decor: 5, 'Serra Calda': 7, 'Serra Fredda': 8 },
    avatar: 'MT',
    email: 'mattia@nicoragarden.it',
    phone: '340 1000011',
    password: '123',
    contractHours: 40,
    color: '#64748b',
    isActive: false,
  },
  {
    id: 'emp-gz-12',
    name: 'Davide',
    locationId: 'gazzada',
    role: 'Serra Calda',
    skills: { Cassa: 6, Fioreria: 5, Decor: 5, 'Serra Calda': 6, 'Serra Fredda': 6 },
    avatar: 'DV',
    email: 'davide@nicoragarden.it',
    phone: '340 1000012',
    password: '123',
    contractHours: 20,
    color: '#3b82f6',
    isActive: false,
  },

  // ==========================================
  // --- VARESE (20 Collaboratori Reali) ---
  // ==========================================
  {
    id: 'emp-va-1',
    name: 'Stefania',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 10, Fioreria: 6, Decor: 7, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'ST',
    email: 'stefania@nicoragarden.it',
    phone: '340 2000001',
    password: '123',
    isManager: true,
    contractHours: 40,
    color: '#ec4899', // Pink
    isActive: true,
  },
  {
    id: 'emp-va-2',
    name: 'Katja',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 5, Fioreria: 10, Decor: 8, 'Serra Calda': 5, 'Serra Fredda': 4 },
    avatar: 'KA',
    email: 'katja@nicoragarden.it',
    phone: '340 2000002',
    password: '123',
    contractHours: 40,
    color: '#f97316', // Orange
    isActive: true,
  },
  {
    id: 'emp-va-3',
    name: 'Luisa',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 6, Fioreria: 9, Decor: 7, 'Serra Calda': 6, 'Serra Fredda': 4 },
    avatar: 'LU',
    email: 'luisa@nicoragarden.it',
    phone: '340 2000003',
    password: '123',
    contractHours: 40,
    color: '#f97316',
    isActive: true,
  },
  {
    id: 'emp-va-4',
    name: 'Giancarla',
    locationId: 'varese',
    role: 'Decor',
    skills: { Cassa: 6, Fioreria: 7, Decor: 10, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'GC',
    email: 'giancarla@nicoragarden.it',
    phone: '340 2000004',
    password: '123',
    contractHours: 40,
    color: '#a855f7', // Decor/Emporio
    isActive: true,
  },
  {
    id: 'emp-va-5',
    name: 'Giovanna',
    locationId: 'varese',
    role: 'Decor',
    skills: { Cassa: 8, Fioreria: 6, Decor: 9, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'GO',
    email: 'giovanna@nicoragarden.it',
    phone: '340 2000005',
    password: '123',
    contractHours: 40,
    color: '#a855f7',
    isActive: true,
  },
  {
    id: 'emp-va-6',
    name: 'Matteo',
    locationId: 'varese',
    role: 'Serra Calda',
    skills: { Cassa: 5, Fioreria: 4, Decor: 5, 'Serra Calda': 10, 'Serra Fredda': 8 },
    avatar: 'MO',
    email: 'matteo@nicoragarden.it',
    phone: '340 2000006',
    password: '123',
    contractHours: 40,
    color: '#eab308',
    isActive: true,
  },
  {
    id: 'emp-va-7',
    name: 'Stefano',
    locationId: 'varese',
    role: 'Serra Calda',
    skills: { Cassa: 4, Fioreria: 3, Decor: 4, 'Serra Calda': 9, 'Serra Fredda': 8 },
    avatar: 'SO',
    email: 'stefano@nicoragarden.it',
    phone: '340 2000007',
    password: '123',
    contractHours: 40,
    color: '#eab308',
    isActive: true,
  },
  {
    id: 'emp-va-8',
    name: 'Andrea',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 3, Fioreria: 2, Decor: 4, 'Serra Calda': 7, 'Serra Fredda': 9 },
    avatar: 'AN',
    email: 'andrea@nicoragarden.it',
    phone: '340 2000008',
    password: '123',
    contractHours: 40,
    color: '#06b6d4',
    isActive: true,
  },
  {
    id: 'emp-va-9',
    name: 'Francesca',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 6, Fioreria: 9, Decor: 8, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'FR',
    email: 'francesca@nicoragarden.it',
    phone: '340 2000009',
    password: '123',
    contractHours: 40,
    color: '#f97316',
    isActive: true,
  },
  {
    id: 'emp-va-10',
    name: 'Cinzia',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 9, Fioreria: 5, Decor: 6, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'CI',
    email: 'cinzia@nicoragarden.it',
    phone: '340 2000010',
    password: '123',
    contractHours: 24,
    color: '#ec4899',
    isActive: true,
  },
  {
    id: 'emp-va-11',
    name: 'Elina',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 4, Fioreria: 4, Decor: 4, 'Serra Calda': 6, 'Serra Fredda': 8 },
    avatar: 'EL',
    email: 'elina.va@nicoragarden.it',
    phone: '340 2000011',
    password: '123',
    contractHours: 24,
    color: '#22c55e',
    isActive: true,
    isMobile: true,
  },
  {
    id: 'emp-va-12',
    name: 'Gionata',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 3, Fioreria: 2, Decor: 4, 'Serra Calda': 7, 'Serra Fredda': 10 },
    avatar: 'GN',
    email: 'gionata@nicoragarden.it',
    phone: '340 2000012',
    password: '123',
    contractHours: 40,
    color: '#22c55e',
    isActive: true,
  },
  {
    id: 'emp-va-13',
    name: 'Giulio',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 4, Fioreria: 3, Decor: 4, 'Serra Calda': 6, 'Serra Fredda': 9 },
    avatar: 'GL',
    email: 'giulio@nicoragarden.it',
    phone: '340 2000013',
    password: '123',
    contractHours: 40,
    color: '#06b6d4',
    isActive: true,
  },
  {
    id: 'emp-va-14',
    name: 'Carlo',
    locationId: 'varese',
    role: 'Decor',
    skills: { Cassa: 4, Fioreria: 2, Decor: 4, 'Serra Calda': 6, 'Serra Fredda': 8 },
    avatar: 'CA',
    email: 'carlo@nicoragarden.it',
    phone: '340 2000014',
    password: '123',
    contractHours: 40,
    color: '#06b6d4',
    isActive: true,
  },
  {
    id: 'emp-va-15',
    name: 'Sara',
    locationId: 'varese',
    role: 'Decor',
    skills: { Cassa: 6, Fioreria: 6, Decor: 7, 'Serra Calda': 6, 'Serra Fredda': 6 },
    avatar: 'SR',
    email: 'sara@nicoragarden.it',
    phone: '340 2000015',
    password: '123',
    contractHours: 30,
    color: '#a855f7',
    isActive: false,
  },
  {
    id: 'emp-va-16',
    name: 'Arianna',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 6, Fioreria: 5, Decor: 6, 'Serra Calda': 5, 'Serra Fredda': 6 },
    avatar: 'AR',
    email: 'arianna@nicoragarden.it',
    phone: '340 2000016',
    password: '123',
    contractHours: 24,
    color: '#ec4899',
    isActive: false,
  },
  {
    id: 'emp-va-17',
    name: 'Gaia',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 5, Fioreria: 6, Decor: 7, 'Serra Calda': 6, 'Serra Fredda': 6 },
    avatar: 'GA',
    email: 'gaia@nicoragarden.it',
    phone: '340 2000017',
    password: '123',
    contractHours: 24,
    color: '#f97316',
    isActive: false,
  },
  {
    id: 'emp-va-18',
    name: 'Claudio',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 3, Fioreria: 2, Decor: 4, 'Serra Calda': 7, 'Serra Fredda': 8 },
    avatar: 'CL',
    email: 'claudio@nicoragarden.it',
    phone: '340 2000018',
    password: '123',
    contractHours: 40,
    color: '#06b6d4',
    isActive: false,
  },
  {
    id: 'emp-va-19',
    name: 'Debora',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 7, Fioreria: 5, Decor: 6, 'Serra Calda': 4, 'Serra Fredda': 4 },
    avatar: 'DB',
    email: 'debora@nicoragarden.it',
    phone: '340 2000019',
    password: '123',
    contractHours: 20,
    color: '#ec4899',
    isActive: false,
  },
  {
    id: 'emp-va-20',
    name: 'Nancy',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 5, Fioreria: 8, Decor: 7, 'Serra Calda': 4, 'Serra Fredda': 4 },
    avatar: 'NA',
    email: 'nancy@nicoragarden.it',
    phone: '340 2000020',
    password: '123',
    contractHours: 20,
    color: '#f97316',
    isActive: false,
  },
];

export const INITIAL_REQUESTS: ShiftRequest[] = [
  {
    id: 'req-1',
    requesterId: 'emp-gz-7', // Denis
    locationId: 'gazzada',
    type: 'swap',
    targetEmployeeId: 'emp-gz-9', // Ivano
    shiftDate: new Date().toISOString().split('T')[0],
    reason: 'Visita medica programmata al mattino',
    status: 'pending',
    createdAt: 'Oggi alle 08:15',
  },
  {
    id: 'req-2',
    requesterId: 'emp-gz-2', // Eleonora
    locationId: 'gazzada',
    type: 'leave',
    shiftDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    reason: 'Ferie programmate',
    status: 'approved',
    createdAt: 'Ieri alle 17:30',
    managerNote: 'Ferie approvate',
  },
  {
    id: 'req-3',
    requesterId: 'emp-va-2', // Katja
    locationId: 'varese',
    type: 'leave',
    shiftDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    reason: 'Permesso speciale fiera floreale',
    status: 'pending',
    createdAt: 'Ieri alle 10:00',
  },
];
