import { Employee, LocationInfo, Shift, ShiftRequest } from './types';
import { generateWeeklySchedule, getSundayOfWeek } from './utils/scheduler';

export const MANAGER_MASTER_PASSWORD = 'admin'; // Password master del responsabile per l'MVP

export const LOCATIONS: LocationInfo[] = [
  {
    id: 'gazzada',
    name: 'Nicora Garden Gazzada',
    shortName: 'Gazzada',
    city: 'Gazzada Schianno (VA)',
    defaultStaffCount: 10,
  },
  {
    id: 'varese',
    name: 'Nicora Garden Varese',
    shortName: 'Varese',
    city: 'Varese Centro',
    defaultStaffCount: 13,
  },
];

export const INITIAL_EMPLOYEES: Employee[] = [
  // --- GAZZADA (10 Collaboratori) ---
  {
    id: 'emp-gz-1',
    name: 'Marco V.',
    locationId: 'gazzada',
    role: 'Serra Calda',
    skills: { Cassa: 7, Fioreria: 5, Decor: 6, 'Serra Calda': 10, 'Serra Fredda': 8 },
    avatar: 'MV',
    email: 'marco@nicoragarden.it',
    password: '123',
    isManager: true,
  },
  {
    id: 'emp-gz-2',
    name: 'Elena R.',
    locationId: 'gazzada',
    role: 'Cassa',
    skills: { Cassa: 10, Fioreria: 4, Decor: 5, 'Serra Calda': 3, 'Serra Fredda': 2 },
    avatar: 'ER',
    email: 'elena@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-3',
    name: 'Cecilia T.',
    locationId: 'gazzada',
    role: 'Fioreria',
    skills: { Cassa: 8, Fioreria: 10, Decor: 7, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'CT',
    email: 'cecilia@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-4',
    name: 'Davide G.',
    locationId: 'gazzada',
    role: 'Cassa',
    skills: { Cassa: 10, Fioreria: 6, Decor: 5, 'Serra Calda': 7, 'Serra Fredda': 6 },
    avatar: 'DG',
    email: 'davide@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-5',
    name: 'Luca B.',
    locationId: 'gazzada',
    role: 'Serra Fredda',
    skills: { Cassa: 3, Fioreria: 2, Decor: 4, 'Serra Calda': 7, 'Serra Fredda': 10 },
    avatar: 'LB',
    email: 'luca@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-6',
    name: 'Chiara M.',
    locationId: 'gazzada',
    role: 'Decor',
    skills: { Cassa: 6, Fioreria: 7, Decor: 10, 'Serra Calda': 3, 'Serra Fredda': 2 },
    avatar: 'CM',
    email: 'chiara@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-7',
    name: 'Simona T.',
    locationId: 'gazzada',
    role: 'Cassa',
    skills: { Cassa: 9, Fioreria: 4, Decor: 6, 'Serra Calda': 3, 'Serra Fredda': 2 },
    avatar: 'ST',
    email: 'simona@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-8',
    name: 'Paolo F.',
    locationId: 'gazzada',
    role: 'Serra Fredda',
    skills: { Cassa: 4, Fioreria: 2, Decor: 3, 'Serra Calda': 8, 'Serra Fredda': 9 },
    avatar: 'PF',
    email: 'paolo@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-9',
    name: 'Valentina B.',
    locationId: 'gazzada',
    role: 'Fioreria',
    skills: { Cassa: 6, Fioreria: 9, Decor: 8, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'VB',
    email: 'valentina@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-gz-10',
    name: 'Matteo R.',
    locationId: 'gazzada',
    role: 'Decor',
    skills: { Cassa: 5, Fioreria: 5, Decor: 9, 'Serra Calda': 6, 'Serra Fredda': 7 },
    avatar: 'MR',
    email: 'matteo@nicoragarden.it',
    password: '123',
  },

  // --- VARESE (13 Collaboratori) ---
  {
    id: 'emp-va-1',
    name: 'Vittore Nicora',
    locationId: 'varese',
    role: 'Serra Calda',
    skills: { Cassa: 8, Fioreria: 8, Decor: 8, 'Serra Calda': 10, 'Serra Fredda': 10 },
    avatar: 'VN',
    email: 'vittore@nicoragarden.it',
    password: 'admin',
    isManager: true,
  },
  {
    id: 'emp-va-2',
    name: 'Andrea P.',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 10, Fioreria: 5, Decor: 7, 'Serra Calda': 7, 'Serra Fredda': 6 },
    avatar: 'AP',
    email: 'andrea@nicoragarden.it',
    password: '123',
    isManager: true,
  },
  {
    id: 'emp-va-3',
    name: 'Silvia M.',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 7, Fioreria: 10, Decor: 8, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'SM',
    email: 'silvia@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-4',
    name: 'Roberto C.',
    locationId: 'varese',
    role: 'Serra Calda',
    skills: { Cassa: 5, Fioreria: 4, Decor: 4, 'Serra Calda': 10, 'Serra Fredda': 9 },
    avatar: 'RC',
    email: 'roberto@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-5',
    name: 'Francesca L.',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 10, Fioreria: 6, Decor: 6, 'Serra Calda': 3, 'Serra Fredda': 3 },
    avatar: 'FL',
    email: 'francesca@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-6',
    name: 'Giorgio D.',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 3, Fioreria: 2, Decor: 3, 'Serra Calda': 7, 'Serra Fredda': 10 },
    avatar: 'GD',
    email: 'giorgio@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-7',
    name: 'Giulia B.',
    locationId: 'varese',
    role: 'Decor',
    skills: { Cassa: 6, Fioreria: 7, Decor: 10, 'Serra Calda': 3, 'Serra Fredda': 3 },
    avatar: 'GB',
    email: 'giulia@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-8',
    name: 'Stefano F.',
    locationId: 'varese',
    role: 'Serra Calda',
    skills: { Cassa: 4, Fioreria: 3, Decor: 4, 'Serra Calda': 10, 'Serra Fredda': 8 },
    avatar: 'SF',
    email: 'stefano@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-9',
    name: 'Laura G.',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 9, Fioreria: 8, Decor: 5, 'Serra Calda': 4, 'Serra Fredda': 3 },
    avatar: 'LG',
    email: 'laura@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-10',
    name: 'Carlo V.',
    locationId: 'varese',
    role: 'Decor',
    skills: { Cassa: 4, Fioreria: 5, Decor: 9, 'Serra Calda': 6, 'Serra Fredda': 6 },
    avatar: 'CV',
    email: 'carlo@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-11',
    name: 'Monica S.',
    locationId: 'varese',
    role: 'Fioreria',
    skills: { Cassa: 6, Fioreria: 9, Decor: 7, 'Serra Calda': 3, 'Serra Fredda': 3 },
    avatar: 'MS',
    email: 'monica@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-12',
    name: 'Alessandro N.',
    locationId: 'varese',
    role: 'Serra Fredda',
    skills: { Cassa: 4, Fioreria: 3, Decor: 4, 'Serra Calda': 8, 'Serra Fredda': 10 },
    avatar: 'AN',
    email: 'alessandro@nicoragarden.it',
    password: '123',
  },
  {
    id: 'emp-va-13',
    name: 'Elisa M.',
    locationId: 'varese',
    role: 'Cassa',
    skills: { Cassa: 9, Fioreria: 5, Decor: 6, 'Serra Calda': 3, 'Serra Fredda': 2 },
    avatar: 'EM',
    email: 'elisa@nicoragarden.it',
    password: '123',
  },
];

export const INITIAL_REQUESTS: ShiftRequest[] = [
  {
    id: 'req-1',
    requesterId: 'emp-gz-5', // Luca B.
    locationId: 'gazzada',
    type: 'swap',
    targetEmployeeId: 'emp-gz-8', // Paolo F.
    shiftDate: new Date().toISOString().split('T')[0],
    reason: 'Visita dal dentista programmata al mattino',
    status: 'pending',
    createdAt: 'Oggi alle 08:15',
  },
  {
    id: 'req-2',
    requesterId: 'emp-gz-3', // Cecilia T.
    locationId: 'gazzada',
    type: 'leave',
    shiftDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    reason: 'Gita in montagna programmata (giorno di riposo desiderato)',
    status: 'approved',
    createdAt: 'Ieri alle 17:30',
  },
  {
    id: 'req-3',
    requesterId: 'emp-va-3', // Silvia M.
    locationId: 'varese',
    type: 'leave',
    shiftDate: new Date(Date.now() + 86400000 * 3).toISOString().split('T')[0],
    reason: 'Permesso speciale fiera floreale',
    status: 'pending',
    createdAt: 'Ieri alle 10:00',
  },
];

// Generatore orari realistici per entrambe le sedi
export const generateInitialMockShifts = (): Shift[] => {
  const currentSunday = getSundayOfWeek(new Date());
  const sundayStr = currentSunday.toISOString().split('T')[0];

  const gazzadaResult = generateWeeklySchedule({
    locationId: 'gazzada',
    employees: INITIAL_EMPLOYEES,
    weekStartDate: sundayStr,
    requests: INITIAL_REQUESTS,
    mode: 'standard',
  });

  const vareseResult = generateWeeklySchedule({
    locationId: 'varese',
    employees: INITIAL_EMPLOYEES,
    weekStartDate: sundayStr,
    requests: INITIAL_REQUESTS,
    mode: 'standard',
  });

  return [...gazzadaResult.shifts, ...vareseResult.shifts];
};
